Repository ttoklip/BackEnd, pull requests merged in 2024-08, with the labels that each got.

#185 setting: Change DB Source
  src/main/resources/application.yml
Labels: :wrench: Setting, 임준형

#186 fix: createCode change only number
  src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
Labels: :bug: BugFix, 임준형

#188 feat: newsletter create admin
  src/main/java/com/api/ttoklip/domain/newsletter/post/controller/NewsletterController.java
  src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
Labels: :sparkles: Feature, 문종근

#191 fix: community 잘못된 페이징 쿼리 수정
  src/main/java/com/api/ttoklip/domain/mypage/domain/MyCommunityPagingRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/service/MyPageService.java
Labels: :bug: BugFix, 임준형

#193 pr Docs/11 design swagger ui
  src/main/resources/META-INF/MANIFEST.MF
  src/main/resources/META-INF/maven/org.webjars/swagger-ui/pom.properties
  src/main/resources/META-INF/maven/org.webjars/swagger-ui/pom.xml
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/favicon-16x16.png
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/favicon-32x32.png
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/index.css
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/index.css.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/index.html
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/index.html.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/oauth2-redirect.html
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/oauth2-redirect.html.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-initializer.js
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-initializer.js.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-bundle.js
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-bundle.js.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-bundle.js.map
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-es-bundle-core.js
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-es-bundle-core.js.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-es-bundle-core.js.map
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-es-bundle.js
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-es-bundle.js.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-es-bundle.js.map
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-standalone-preset.js
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-standalone-preset.js.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui-standalone-preset.js.map
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui.css
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui.css.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui.css.map
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui.js
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui.js.gz
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/swagger-ui.js.map
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/ttokleap_logo.png
  src/main/resources/META-INF/resources/webjars/swagger-ui/5.2.0/ttokleap_slogan.png
Labels: :memo: Docs, :twisted_rightwards_arrows: PullRequest, 문종근

#196 pr Fix/24 exclude duplicate setting
  build.gradle
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 문종근
