Repository ttoklip/BackEnd, pull requests merged in 2024-02, with the labels that each got.

#47 pr Fix/2 newsletter main get
  src/main/java/com/api/ttoklip/domain/newsletter/image/domain/NewsletterImage.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/controller/NewsletterMainController.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/CategoryResponse.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/CategoryResponses.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/NewsletterCategoryRes.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/NewsletterMainRes.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/NewsletterMainResponse.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/RandomTitleResponse.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/service/NewsletterMainService.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/service/NewsletterScheduler.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/domain/Newsletter.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/domain/TodayNewsletter.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/domain/repository/NewsletterQueryDslRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/dto/request/NewsletterCreateReq.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterDefaultRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/TodayNewsletterRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
  src/main/java/com/api/ttoklip/global/config/SchedulingConfig.java
  src/main/java/com/api/ttoklip/global/s3/S3FileUploader.java
  src/main/java/com/api/ttoklip/global/util/TimeUtil.java
  src/main/resources/application.yml
Labels: :ambulance: BREAKING CHANGE, :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 임준형

#48 pr Feat/8 search api
  src/main/java/com/api/ttoklip/domain/common/comment/repository/CommentRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/common/search/constant/SearchResponseConstant.java
  src/main/java/com/api/ttoklip/domain/common/search/controller/SearchController.java
  src/main/java/com/api/ttoklip/domain/common/search/response/CommunityPaging.java
  src/main/java/com/api/ttoklip/domain/common/search/response/CommunitySingleResponse.java
  src/main/java/com/api/ttoklip/domain/common/search/response/HoneyTipPaging.java
  src/main/java/com/api/ttoklip/domain/common/search/response/NewsletterPaging.java
  src/main/java/com/api/ttoklip/domain/common/search/response/SingleResponse.java
  src/main/java/com/api/ttoklip/domain/common/search/service/SearchService.java
  src/main/java/com/api/ttoklip/domain/honeytip/comment/controller/HoneyTipCommentController.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/controller/HoneyTipPostController.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipDefaultRepository.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipRepository.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipSearchRepository.java
  src/main/java/com/api/ttoklip/domain/main/controller/CommonController.java
  src/main/java/com/api/ttoklip/domain/main/service/CommonService.java
  src/main/java/com/api/ttoklip/domain/newsletter/comment/controller/NewsletterCommentController.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/constant/NewsletterResponseConstant.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/controller/NewsletterMainController.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/controller/NewsletterController.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterDefaultRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterSearchRepository.java
  src/main/java/com/api/ttoklip/domain/question/comment/controller/QuestionCommentController.java
  src/main/java/com/api/ttoklip/domain/question/post/controller/QuestionPostController.java
  src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionDefaultRepository.java
  src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunitySearchRepository.java
  src/main/java/com/api/ttoklip/global/health/HealthCheckController.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 임준형

#50 Feat/9 로그인 회원가입 기능 구현
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/constant/FindIdConstant.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/constant/ResetPwConstant.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/controller/FindIdController.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/controller/ResetPwController.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/dto/request/FindIdRequest.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/dto/request/ResetPwRequest.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/dto/response/FindIdResponse.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/dto/response/ResetPwResponse.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/service/FindIdService.java
  src/main/java/com/api/ttoklip/domain/FindidAndFindpw/main/service/ResetPwService.java
  src/main/java/com/api/ttoklip/domain/Login/main/constant/LoginResponseConstant.java
  src/main/java/com/api/ttoklip/domain/Login/main/controller/LoginController.java
  src/main/java/com/api/ttoklip/domain/Login/main/dto/request/LoginCondition.java
  src/main/java/com/api/ttoklip/domain/Login/main/dto/response/LoginResponse.java
  src/main/java/com/api/ttoklip/domain/Login/main/service/LoginService.java
  src/main/java/com/api/ttoklip/domain/SignUp/image/dto/response/ImageResponse.java
  src/main/java/com/api/ttoklip/domain/SignUp/main/constant/SignUpResponseConstant.java
  src/main/java/com/api/ttoklip/domain/SignUp/main/controller/SignUpController.java
  src/main/java/com/api/ttoklip/domain/SignUp/main/dto/request/SignUpCondition.java
  src/main/java/com/api/ttoklip/domain/SignUp/main/dto/response/SignUpResponse.java
  src/main/java/com/api/ttoklip/domain/SignUp/main/service/SignUpService.java
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/member/domain/Role.java
  src/main/java/com/api/ttoklip/domain/member/repository/MemberOAuthRepository.java
  src/main/java/com/api/ttoklip/domain/member/repository/MemberRepository.java
  src/main/java/com/api/ttoklip/domain/member/service/MemberService.java
  src/main/java/com/api/ttoklip/domain/profile/domain/Profile.java
  src/main/java/com/api/ttoklip/domain/profile/repository/ProfileRepository.java
  src/main/java/com/api/ttoklip/domain/profile/service/ProfileService.java
  src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
  src/main/java/com/api/ttoklip/global/security/oauth/controller/OAuthController.java
  src/main/java/com/api/ttoklip/global/security/oauth/handler/CustomOAuthFailureHandler.java
  src/main/java/com/api/ttoklip/global/security/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/api/ttoklip/global/security/oauth/principal/CustomOAuth2User.java
  src/main/java/com/api/ttoklip/global/security/oauth/response/AuthResponse.java
  src/main/java/com/api/ttoklip/global/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/api/ttoklip/global/security/oauth/userInfo/KakaoUserInfo.java
  src/main/java/com/api/ttoklip/global/security/oauth/userInfo/NaverUserInfo.java
  src/main/java/com/api/ttoklip/global/security/oauth/userInfo/OAuth2UserInfo.java
  src/main/java/com/api/ttoklip/global/security/oauth/userInfo/OAuthUserInfoFactory.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 임준형

#55 fix web 로그인 방식 sdk 로그인 방식 활용
  src/main/java/com/api/ttoklip/domain/common/base/BaseEntityConfig.java
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/member/repository/MemberRepository.java
  src/main/java/com/api/ttoklip/domain/member/service/MemberService.java
  src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
  src/main/java/com/api/ttoklip/global/security/auth/controller/AuthController.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/LoginRequest.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/LoginResponse.java
  src/main/java/com/api/ttoklip/global/security/auth/handler/AuthFailureHandler.java
  src/main/java/com/api/ttoklip/global/security/auth/handler/TokenErrorHandler.java
  src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
  src/main/java/com/api/ttoklip/global/security/auth/service/OAuth2UserInfoFactory.java
  src/main/java/com/api/ttoklip/global/security/auth/userInfo/KakaoUserInfo.java
  src/main/java/com/api/ttoklip/global/security/auth/userInfo/NaverUserInfo.java
  src/main/java/com/api/ttoklip/global/security/auth/userInfo/OAuth2UserInfo.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
  src/main/java/com/api/ttoklip/global/security/oauth/controller/OAuthController.java
  src/main/java/com/api/ttoklip/global/security/oauth/handler/CustomOAuthSuccessHandler.java
  src/main/java/com/api/ttoklip/global/security/oauth/principal/CustomOAuth2User.java
  src/main/java/com/api/ttoklip/global/security/oauth/response/AuthResponse.java
  src/main/java/com/api/ttoklip/global/security/oauth/service/CustomOAuth2UserService.java
  src/main/java/com/api/ttoklip/global/security/oauth/userInfo/OAuthUserInfoFactory.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 임준형

#56 pr fix web 로그인 방식 sdk 로그인 방식 활용
  src/main/java/com/api/ttoklip/domain/privacy/constant/PrivacyConstant.java
  src/main/java/com/api/ttoklip/domain/privacy/controller/ProfileController.java
  src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
  src/main/java/com/api/ttoklip/global/security/auth/controller/AuthController.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/LoginRequest.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
  src/main/resources/application.yml
Labels: :bug: BugFix, :sparkles: Feature, 임준형

#59 pr Fix/4 invalid oauth accesstoken error custom
  build.gradle
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
  src/main/java/com/api/ttoklip/global/security/auth/service/OAuth2UserInfoFactory.java
  src/main/java/com/api/ttoklip/global/security/auth/userInfo/KakaoUserInfo.java
  src/main/java/com/api/ttoklip/global/security/auth/userInfo/NaverUserInfo.java
Labels: :ambulance: BREAKING CHANGE, :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 임준형

#62 pr Feat/9 우리동네 좋아요 스크랩 기능 구현
  .gitignore
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/town/cart/constant/CartResponseConstant.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/request/UpdateStatusRequest.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/entity/Cart.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/entity/TradeStatus.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
  src/main/java/com/api/ttoklip/domain/town/community/comment/service/CommunityCommentService.java
  src/main/java/com/api/ttoklip/domain/town/community/constant/CommunityResponseConstant.java
  src/main/java/com/api/ttoklip/domain/town/community/like/entity/CommunityLike.java
  src/main/java/com/api/ttoklip/domain/town/community/like/repository/CommunityLikeRepository.java
  src/main/java/com/api/ttoklip/domain/town/community/like/repository/CommunityLikeRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/town/community/like/repository/CommunityLikeRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/community/like/service/CommunityLikeService.java
  src/main/java/com/api/ttoklip/domain/town/community/post/controller/CommunityPostController.java
  src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CommunitySingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/community/post/entity/Community.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepository.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityCommonService.java
  src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
  src/main/java/com/api/ttoklip/domain/town/community/scrap/entity/CommunityScrap.java
  src/main/java/com/api/ttoklip/domain/town/community/scrap/repository/CommunityScrapRepository.java
  src/main/java/com/api/ttoklip/domain/town/community/scrap/repository/CommunityScrapRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/town/community/scrap/repository/CommunityScrapRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/community/scrap/service/CommunityScrapService.java
  src/main/java/com/api/ttoklip/domain/town/main/constant/TownResponseConstant.java
  src/main/java/com/api/ttoklip/domain/town/main/controller/TownMainController.java
  src/main/java/com/api/ttoklip/domain/town/main/dto/response/TownMainResponse.java
  src/main/java/com/api/ttoklip/domain/town/main/dto/response/TownSearchResponse.java
  src/main/java/com/api/ttoklip/domain/town/main/dto/response/TownTitleResponse.java
  src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/LoginRequest.java
  src/main/java/com/api/ttoklip/global/success/Message.java
  src/main/resources/application.yml
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 문종근

#64 pr Feat/9 우리동네 좋아요, 스크랩 빌드 오류 수정
  src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityCommonService.java
Labels: :bug: BugFix, 문종근

#69 pr Fix/6 뉴스레터 단건조회수정
  src/main/java/com/api/ttoklip/domain/honeytip/post/domain/HoneyTip.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/service/HoneyTipPostService.java
  src/main/java/com/api/ttoklip/domain/honeytip/scrap/domain/HoneyTipScrap.java
  src/main/java/com/api/ttoklip/domain/honeytip/scrap/repository/HoneyTipScrapRepository.java
  src/main/java/com/api/ttoklip/domain/honeytip/scrap/repository/HoneyTipScrapRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/honeytip/scrap/service/HoneyTipScrapService.java
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/dto/response/NewsletterSingleResponse.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 문종근

#71 pr Fix/7 query dsl import error
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipDefaultRepository.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipRepositoryImpl.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 문종근

#73 Feat/11 mypage api
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/mypage/main/constant/MyPageConstant.java
  src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
  src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyCommunityRepostiory.java
  src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyHoneyTipRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyNewsLetterRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyQuestionRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/request/BlockedRequest.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/request/ProfileEditRequest.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/BlockedListResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/BlockedResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/MyPageResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/MyPostsListResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/MyPostsResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/ParticipateListResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/ParticipateResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/RestricetdResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/ScrapPostResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/UserSingleResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/service/MyPageService.java
  src/main/java/com/api/ttoklip/domain/mypage/noti/post/controller/NoticeController.java
  src/main/java/com/api/ttoklip/domain/mypage/term/controller/TermController.java
  src/main/java/com/api/ttoklip/domain/privacy/domain/Profile.java
  src/main/java/com/api/ttoklip/global/success/Message.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 박세준

#75 pr Feat/14 like scrap value
  src/main/java/com/api/ttoklip/domain/honeytip/like/service/HoneyTipLikeService.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/dto/response/HoneyTipSingleResponse.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/service/HoneyTipPostService.java
  src/main/java/com/api/ttoklip/domain/honeytip/scrap/service/HoneyTipScrapService.java
  src/main/java/com/api/ttoklip/domain/newsletter/like/service/NewsletterLikeService.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/dto/response/NewsletterSingleResponse.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
  src/main/java/com/api/ttoklip/domain/newsletter/scarp/service/NewsletterScrapService.java
  src/main/java/com/api/ttoklip/domain/town/community/like/service/CommunityLikeService.java
  src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CommunitySingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
  src/main/java/com/api/ttoklip/domain/town/community/scrap/service/CommunityScrapService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 임준형

#77 fix: 사진 크키 제한 설정
  src/main/resources/application.yml
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 임준형

#79 pr Feat/10 search api apply response field
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipSearchRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterSearchRepository.java
  src/main/java/com/api/ttoklip/domain/search/controller/SearchController.java
  src/main/java/com/api/ttoklip/domain/search/response/CommunitySingleResponse.java
  src/main/java/com/api/ttoklip/domain/search/response/SingleResponse.java
  src/main/java/com/api/ttoklip/domain/search/service/SearchService.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunitySearchRepository.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 임준형

#83 pr Fix/10 main categories honeytip deactivity post fiilter
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipDefaultRepository.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipSearchRepository.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunitySearchRepository.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 임준형

#82 pr Feat/15 question comment like, likedByCurrentUser value
  src/main/java/com/api/ttoklip/domain/main/constant/QuestionResponseConstant.java
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/question/comment/controller/QuestionCommentController.java
  src/main/java/com/api/ttoklip/domain/question/comment/domain/QuestionComment.java
  src/main/java/com/api/ttoklip/domain/question/comment/service/QuestionCommentService.java
  src/main/java/com/api/ttoklip/domain/question/like/entity/CommentLike.java
  src/main/java/com/api/ttoklip/domain/question/like/repository/CommentLikeRepository.java
  src/main/java/com/api/ttoklip/domain/question/like/repository/CommentLikeRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/question/like/service/CommentLikeService.java
  src/main/java/com/api/ttoklip/domain/question/post/controller/QuestionPostController.java
  src/main/java/com/api/ttoklip/domain/question/post/domain/Question.java
  src/main/java/com/api/ttoklip/domain/question/post/dto/response/QuestionSingleResponse.java
  src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/question/post/service/QuestionCommonService.java
  src/main/java/com/api/ttoklip/domain/question/post/service/QuestionPostService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 문종근

#89 setting: 태스크 정의 한국으로 고정
  aws/task_definition.json
Labels: :wrench: Setting, 임준형, :construction_worker: CI/CD

#93 pr Refactor/2 cart party, party delete, party count
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/town/cart/constant/CartResponseConstant.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/request/CartCreateRequest.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/entity/Cart.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/entity/CartMember.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartMemberRepository.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartMemberRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartMemberService.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
  src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
  src/main/java/com/api/ttoklip/global/success/Message.java
Labels: :recycle: Refactor, :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 문종근, 박세준

#97 Feat/19 home weather api connect todo list
  src/main/java/com/api/ttoklip/domain/common/base/BaseEntity.java
  src/main/java/com/api/ttoklip/domain/common/base/BaseEntityConfig.java
  src/main/java/com/api/ttoklip/domain/common/base/BaseTimeEntity.java
  src/main/java/com/api/ttoklip/domain/home/controller/HomeController.java
  src/main/java/com/api/ttoklip/domain/home/response/HomeResponse.java
  src/main/java/com/api/ttoklip/domain/home/service/HomeService.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/post/dto/response/HoneytipSingleResponse.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/repository/HoneyTipRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/service/HoneyTipPostService.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/constant/NewsletterResponseConstant.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/controller/NewsletterMainController.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/CategoryResponses.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/NewsCategoryPagingResponse.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/dto/response/NewsletterThumbnailResponse.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/service/NewsletterMainService.java
  src/main/java/com/api/ttoklip/domain/newsletter/main/service/NewsletterScheduler.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/controller/NewsletterController.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepository.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/repository/NewsletterQueryDslRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/service/NewsletterPostService.java
  src/main/java/com/api/ttoklip/domain/question/image/service/QuestionImageService.java
  src/main/java/com/api/ttoklip/domain/todolist/TodayToDoResponse.java
  src/main/java/com/api/ttoklip/domain/todolist/domain/ToDoList.java
  src/main/java/com/api/ttoklip/domain/todolist/domain/ToDoListScheduler.java
  src/main/java/com/api/ttoklip/domain/todolist/domain/TodayToDoList.java
  src/main/java/com/api/ttoklip/domain/todolist/domain/TodayToDoListRepository.java
  src/main/java/com/api/ttoklip/domain/todolist/domain/TodayToDoListRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/todolist/domain/TodayToRoListCustomRepository.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 임준형

#103 fix: weatherService 제거, @Builder.Default 적용
  src/main/java/com/api/ttoklip/domain/home/service/HomeService.java
  src/main/java/com/api/ttoklip/domain/town/community/post/entity/Community.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 임준형

#98 feat: 마이페이지 질문해요 페이징 기능 구현
  src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/QuestionPaging.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/UserSingleResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/service/MyPageService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 박세준

#102 pr Feat/20 community paging
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/question/comment/domain/QuestionComment.java
  src/main/java/com/api/ttoklip/domain/question/comment/dto/response/QuestionCommentResponse.java
  src/main/java/com/api/ttoklip/domain/question/comment/service/QuestionCommentService.java
  src/main/java/com/api/ttoklip/domain/question/like/entity/CommentLike.java
  src/main/java/com/api/ttoklip/domain/question/like/service/CommentLikeService.java
  src/main/java/com/api/ttoklip/domain/question/post/controller/QuestionPostController.java
  src/main/java/com/api/ttoklip/domain/question/post/dto/response/QuestionSingleResponse.java
  src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/question/post/service/QuestionPostService.java
  src/main/java/com/api/ttoklip/domain/search/response/CommunitySingleResponse.java
  src/main/java/com/api/ttoklip/domain/search/response/SingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
  src/main/java/com/api/ttoklip/domain/town/main/constant/TownResponseConstant.java
  src/main/java/com/api/ttoklip/domain/town/main/controller/TownMainController.java
  src/main/java/com/api/ttoklip/domain/town/main/dto/request/TownSearchCondition.java
  src/main/java/com/api/ttoklip/domain/town/main/dto/response/TownMainResponse.java
  src/main/java/com/api/ttoklip/domain/town/main/repository/CommunityPageRepository.java
  src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 문종근

#107 fix: 개인정보 생성 및 수정시 오류 해결
  src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
  src/main/java/com/api/ttoklip/domain/privacy/repository/InterestRepository.java
  src/main/java/com/api/ttoklip/domain/privacy/service/ProfileService.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
Labels: :bug: BugFix, :sparkles: Feature, 임준형

#108 pr fix: 회원정보 생성 및 수정 누락 커밋 추가
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/privacy/service/ProfileService.java
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 임준형

#100 feat: 현재 모집인원 비례 가격으로 구현 완료했습니다
  src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
  src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyCartRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/UserCartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/main/service/MyPageService.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartPaging.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/entity/Cart.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 박세준

#111 pr Feat/24 cart paging
  src/main/java/com/api/ttoklip/domain/search/response/CartSearchPaging.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartSearchRepository.java
  src/main/java/com/api/ttoklip/domain/town/main/constant/TownResponseConstant.java
  src/main/java/com/api/ttoklip/domain/town/main/controller/TownMainController.java
  src/main/java/com/api/ttoklip/domain/town/main/repository/CartPageRepository.java
  src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
Labels: :memo: Docs, :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 문종근, 박세준

#113 Feat/23 home weather api community3 get
  src/main/java/com/api/ttoklip/domain/home/constant/HomeConstant.java
  src/main/java/com/api/ttoklip/domain/home/controller/HomeController.java
  src/main/java/com/api/ttoklip/domain/home/response/HomeResponse.java
  src/main/java/com/api/ttoklip/domain/home/service/HomeService.java
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/member/editor/MemberEditor.java
  src/main/java/com/api/ttoklip/domain/mypage/main/dto/response/UserCartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/privacy/dto/PrivacyCreateRequest.java
  src/main/java/com/api/ttoklip/domain/privacy/service/ProfileService.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 임준형

#115 fix: HomeController 명세서 작성
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/member/editor/MemberEditor.java
  src/main/java/com/api/ttoklip/domain/privacy/dto/PrivacyCreateRequest.java
  src/main/java/com/api/ttoklip/domain/privacy/service/ProfileService.java
Labels: :ambulance: BREAKING CHANGE, :twisted_rightwards_arrows: PullRequest, 임준형

#118 fix: 제한 범위 변경
  src/main/java/com/api/ttoklip/domain/honeytip/post/dto/request/HoneyTipCreateReq.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/dto/request/HoneyTipEditReq.java
  src/main/java/com/api/ttoklip/domain/mypage/noti/post/dto/request/NoticeCreateRequest.java
  src/main/java/com/api/ttoklip/domain/mypage/noti/post/dto/request/NoticeEditRequest.java
  src/main/java/com/api/ttoklip/domain/mypage/term/dto/request/TermCreateRequest.java
  src/main/java/com/api/ttoklip/domain/mypage/term/dto/request/TermEditRequest.java
  src/main/java/com/api/ttoklip/domain/newsletter/post/dto/request/NewsletterCreateReq.java
  src/main/java/com/api/ttoklip/domain/question/post/dto/request/QuestionCreateRequest.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/request/CartCreateRequest.java
  src/main/java/com/api/ttoklip/domain/town/community/post/dto/request/CommunityCreateRequest.java
Labels: :ambulance: BREAKING CHANGE, :twisted_rightwards_arrows: PullRequest, 임준형

#120 feat: 우리동네 메인 - 3개씩 추출
  src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CartMainResponse.java
  src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CommunityRecent3Response.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryCustom.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/community/post/service/CommunityPostService.java
  src/main/java/com/api/ttoklip/domain/town/main/controller/TownMainController.java
  src/main/java/com/api/ttoklip/domain/town/main/service/TownMainService.java
Labels: :sparkles: Feature, 임준형

#122 feat: CartMember 존재하는지에 대한 여부
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 임준형
