Repository ttoklip/BackEnd, pull requests merged in 2024-07, with the labels that each got.

#145 Fix/9 memberservice stranger api
  src/main/java/com/api/ttoklip/domain/member/dto/response/TargetMemberProfile.java
  src/main/java/com/api/ttoklip/domain/member/service/MemberService.java
  src/main/java/com/api/ttoklip/domain/member/service/ProfileLikeService.java
  src/main/java/com/api/ttoklip/domain/stranger/dto/response/StrangerResponse.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
Labels: :bug: BugFix, 임준형

#134 pr Feat/28 join api
  build.gradle
  src/main/java/com/api/ttoklip/domain/email/Repository/EmailRepository.java
  src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
  src/main/java/com/api/ttoklip/domain/email/dto/request/EmailRequest.java
  src/main/java/com/api/ttoklip/domain/email/entity/Email.java
  src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
  src/main/java/com/api/ttoklip/domain/member/domain/Member.java
  src/main/java/com/api/ttoklip/domain/member/repository/MemberRepository.java
  src/main/java/com/api/ttoklip/global/config/EmailAsyncConfig.java
  src/main/java/com/api/ttoklip/global/config/EmailConfig.java
  src/main/java/com/api/ttoklip/global/config/RedisConfig.java
  src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
  src/main/java/com/api/ttoklip/global/security/auth/controller/AuthController.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/LoginResponse.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/request/AuthLoginRequest.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/request/AuthRequest.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/response/AuthLoginResponse.java
  src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtAuthenticationFilter.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
  src/main/java/com/api/ttoklip/global/security/oauth2/controller/OAuthController.java
  src/main/java/com/api/ttoklip/global/security/oauth2/dto/OAuthLoginRequest.java
  src/main/java/com/api/ttoklip/global/security/oauth2/dto/OAuthLoginResponse.java
  src/main/java/com/api/ttoklip/global/security/oauth2/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/api/ttoklip/global/security/oauth2/handler/OAuthFailureHandler.java
  src/main/java/com/api/ttoklip/global/security/oauth2/handler/TokenErrorHandler.java
  src/main/java/com/api/ttoklip/global/security/oauth2/service/OAuth2UserInfoFactory.java
  src/main/java/com/api/ttoklip/global/security/oauth2/service/OAuthService.java
  src/main/java/com/api/ttoklip/global/security/oauth2/userInfo/KakaoUserInfo.java
  src/main/java/com/api/ttoklip/global/security/oauth2/userInfo/NaverUserInfo.java
  src/main/java/com/api/ttoklip/global/security/oauth2/userInfo/OAuth2UserInfo.java
  src/main/java/com/api/ttoklip/global/success/Message.java
  src/main/java/com/api/ttoklip/global/util/RedisUtil.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 문종근

#143 Refactor/5 delete not use mypage api
  src/main/java/com/api/ttoklip/domain/mypage/alam/constant/AlamConstant.java
  src/main/java/com/api/ttoklip/domain/mypage/alam/controller/AlamController.java
  src/main/java/com/api/ttoklip/domain/mypage/alam/dto/request/AlamRequest.java
  src/main/java/com/api/ttoklip/domain/mypage/alam/service/AlamService.java
  src/main/java/com/api/ttoklip/domain/mypage/ban/constant/BanConstant.java
  src/main/java/com/api/ttoklip/domain/mypage/ban/controller/BanController.java
  src/main/java/com/api/ttoklip/domain/mypage/ban/service/BanService.java
  src/main/java/com/api/ttoklip/domain/mypage/main/constant/MyPageConstant.java
  src/main/java/com/api/ttoklip/domain/mypage/main/controller/MyPageController.java
  src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyCartRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/main/domain/MyCommunityRepostiory.java
  src/main/java/com/api/ttoklip/domain/mypage/main/service/MyPageService.java
Labels: :recycle: Refactor, 박세준

#153 pr Feat/34 design email form
  build.gradle
  src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
  src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
  src/main/java/com/api/ttoklip/global/config/AsyncConfig.java
  src/main/java/com/api/ttoklip/global/config/EmailAsyncConfig.java
  src/main/resources/templates/mail.html
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 문종근

#158 pr Docs/8 separating email requests
  src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
  src/main/java/com/api/ttoklip/domain/email/dto/request/EmailSendRequest.java
  src/main/java/com/api/ttoklip/domain/email/dto/request/EmailVerifyRequest.java
  src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
Labels: :memo: Docs, :twisted_rightwards_arrows: PullRequest, 문종근

#161 pr del: 미사용 코드 삭제
  src/main/java/com/api/ttoklip/domain/email/Repository/EmailRepository.java
  src/main/java/com/api/ttoklip/domain/email/entity/Email.java
Labels: :recycle: Refactor, :twisted_rightwards_arrows: PullRequest, 문종근

#165 pr Feat/31 check cart members
  src/main/java/com/api/ttoklip/domain/email/controller/EmailController.java
  src/main/java/com/api/ttoklip/domain/email/service/EmailService.java
  src/main/java/com/api/ttoklip/domain/privacy/dto/InterestResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/constant/CartResponseConstant.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/controller/CartPostController.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartGroupMemberResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartMemberResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/service/CartPostService.java
  src/main/java/com/api/ttoklip/global/exception/ErrorType.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/request/AuthRequest.java
  src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
Labels: :sparkles: Feature, :twisted_rightwards_arrows: PullRequest, 박세준

#167 pr Fix/18 modify email form
  src/main/resources/templates/mail.html
Labels: :bug: BugFix, :twisted_rightwards_arrows: PullRequest, 문종근

#173 pr Fix/20 회원가입 전용 이용약관 조회 api
  src/main/java/com/api/ttoklip/domain/term/controller/TermController.java
  src/main/java/com/api/ttoklip/domain/term/dto/response/TermAdminResponse.java
  src/main/java/com/api/ttoklip/domain/term/repository/TermAgreementRepository.java
  src/main/java/com/api/ttoklip/domain/term/service/TermService.java
  src/main/java/com/api/ttoklip/global/config/SecurityConfig.java
  src/main/java/com/api/ttoklip/global/security/auth/controller/AuthController.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/response/TermClientResponse.java
  src/main/java/com/api/ttoklip/global/security/auth/dto/response/TermSignUpResponse.java
  src/main/java/com/api/ttoklip/global/security/auth/service/AuthService.java
  src/main/java/com/api/ttoklip/global/security/jwt/JwtProvider.java
Labels: :sparkles: Feature, 임준형

#179 pr Fix/21 profile post ripple
  src/main/java/com/api/ttoklip/domain/common/comment/dto/response/CommentResponse.java
  src/main/java/com/api/ttoklip/domain/honeytip/post/dto/response/HoneyTipSingleResponse.java
  src/main/java/com/api/ttoklip/domain/main/dto/response/TitleResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/domain/MyCartRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/domain/MyCommunityRepostiory.java
  src/main/java/com/api/ttoklip/domain/mypage/domain/MyHoneyTipRepository.java
  src/main/java/com/api/ttoklip/domain/mypage/dto/response/UserCartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/mypage/dto/response/UserSingleResponse.java
  src/main/java/com/api/ttoklip/domain/question/comment/dto/response/QuestionCommentResponse.java
  src/main/java/com/api/ttoklip/domain/question/comment/repository/QuestionCommentRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/question/comment/service/QuestionCommentService.java
  src/main/java/com/api/ttoklip/domain/question/post/controller/QuestionPostController.java
  src/main/java/com/api/ttoklip/domain/question/post/dto/response/QuestionSingleResponse.java
  src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionDefaultRepository.java
  src/main/java/com/api/ttoklip/domain/question/post/repository/QuestionRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/search/response/CommunitySingleResponse.java
  src/main/java/com/api/ttoklip/domain/search/response/SingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/dto/response/CartSingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/cart/post/repository/CartSearchRepository.java
  src/main/java/com/api/ttoklip/domain/town/community/post/dto/response/CommunitySingleResponse.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunityRepositoryImpl.java
  src/main/java/com/api/ttoklip/domain/town/community/post/repository/CommunitySearchRepository.java
Labels: :sparkles: Feature, 임준형, 박세준, :heavy_plus_sign: Add
